version: 2

python:
  install:
    - requirements: requirements.in
    - requirements: requirements-dev.in
    - method: pip
      path: .

build:
  os: ubuntu-24.04
  tools:
    python: "3"

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false
