#!/usr/bin/env python
# Copyright (c) Jean-Charles Lefebvre
# SPDX-License-Identifier: MIT

import os.path
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from fitdecode.cmd import fitjson

if __name__ == '__main__':
    sys.exit(fitjson.main())
