#!/usr/bin/env python3
# Copyright (c) Jean-Charles Lefebvre
# SPDX-License-Identifier: MIT

if __name__ == "__main__":
    import os.path
    import sys

    if not sys.flags.optimize:
        sys.dont_write_bytecode = True

    sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

    from fitdecode.cmd import fittxt

    sys.exit(fittxt.main())
